# Generated by Django 5.1 on 2024-09-02 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(default='Default Name', max_length=255)),
                ('number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=255)),
                ('status', models.CharField(default='user', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BatchDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50)),
                ('total_images_inspected', models.PositiveIntegerField()),
                ('total_defected_images', models.PositiveIntegerField()),
                ('total_non_defected_images', models.PositiveIntegerField()),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_details', to='users.user')),
            ],
        ),
    ]
