# Generated by Django 5.1 on 2024-11-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_admindetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchdetail',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('inprogress', 'In Progress')], default='inprogress', max_length=20),
        ),
    ]
