# Generated by Django 5.1 on 2024-11-15 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_state_alter_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='batch_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('batch_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='users.batchdetail')),
            ],
        ),
    ]
