# Generated by Django 5.1 on 2024-11-15 07:25

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_batchimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchimage',
            name='image',
            field=models.ImageField(upload_to=users.models.batch_image_path),
        ),
    ]
