# Generated by Django 5.1.4 on 2025-04-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_instrument_defect'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchdetail',
            name='instrument',
            field=models.CharField(blank=True, choices=[('Bandage Scissor', 'Bandage Scissor'), ('Carver', 'Carver'), ('Dressing Forcep', 'Dressing Forcep'), ('Ex-Probe', 'Ex-Probe'), ('Mcindoe Forcep', 'Mcindoe Forcep'), ('Nail Clipper', 'Nail Clipper'), ('Probe', 'Probe'), ('Scalpal', 'Scalpal'), ('Scissor', 'Scissor'), ('Teale Vulsellum Forceps', 'Teale Vulsellum Forceps'), ('Uterine Curette', 'Uterine Curette')], max_length=50, null=True),
        ),
    ]
